// Snippet: CLI Command Handler
// Description: Template for adding new CLI commands
// Language: ts
// Generated by Chat GitHub PWA

const handleNewCommand = async (arg: string) => {
  if (!arg) {
    addHistory('Usage: /command <argument>');
    return;
  }

  try {
    // Command logic here
    addHistory(`Command executed successfully: ${arg}`);
  } catch (error) {
    addHistory(`Error: ${error instanceof Error ? error.message : String(error)}`);
  }
};