// Snippet: GitHub API Service Method
// Description: Template for adding methods to GitHub service class
// Language: ts
// Generated by Chat GitHub PWA

async methodName(param: string): Promise<ResponseType> {
  try {
    const data = await this.request(`endpoint/${param}`, {
      method: 'GET', // or POST, PUT, DELETE
      // body: JSON.stringify(requestBody), // for POST/PUT
    });
    
    return data;
  } catch (error) {
    throw new Error(`Failed to perform operation: ${error}`);
  }
}